version: "3.9"
services:
  tracksabout-client:
    container_name: 'tracksabout-client'
    # We need to setup ENV in container, --env-file sets variables only in docker-compose context.
    # Use like: ENV_FILE=.env.production docker-compose build
    env_file: ${ENV_FILE}
    build: .
    volumes:
      - /data/www:/data/www
    # WARNING! ENV variables are read from .env file which has to be copied to container - do not ignore .env in .dockerignore!
