version: "3.9"
services:
  tracksabout-client:
    build: .
    ports:
      # For now, app is running in development mode where app is always on 3000. It will change when production app will be accessible via nginx.
      - "3000:3000"
    volumes:
      # Maps cert files from server in app to use HTTPS.
      - ../certs:/certs
    # WARNING! ENV variables are read from .env file which has to be copied to container - do not ignore .env in .dockerignore!
